module AST


type VARIABLE = string

type LINE_NUMBER = int

type VALUE = int

type EQUAL_CONDITION = VARIABLE * VALUE

type OPERATOR_TYPE = 
  | SUM
  | SUBSTRACT
  
type ASSIGN_TYPE = ASSIGN_VALUE of VARIABLE * VALUE | ASSIGN_VARIABLE of VARIABLE * VARIABLE
type Ast = 
  | IF of EQUAL_CONDITION * Ast list
  | IFNOT of EQUAL_CONDITION * Ast list
  | BREAK
  | GOTO of LINE_NUMBER
  | ENTRIPOINT
  | RETURN of VARIABLE
  | ASSIGN of ASSIGN_TYPE
  | OPERATOR of OPERATOR_TYPE * VARIABLE
  | REFLECTION of VARIABLE
  | CONSOLEOUT of VARIABLE
  | CONSOLEIN of VARIABLE
  | NOTHIN